{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ordpens
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ordPens_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ordPens/ordPens_{{ version }}.tar.gz
  sha256: e11a0f9ef67d673ec99b449fb93e617e733f6f61f3ff9cb00fc70bf2b36867a0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rlrsim
    - r-glmpath
    - r-grplasso
    - r-mgcv
    - r-ordinalnet
    - r-quadprog
  run:
    - r-base
    - r-rlrsim
    - r-glmpath
    - r-grplasso
    - r-mgcv
    - r-ordinalnet
    - r-quadprog

test:
  commands:
    - $R -e "library('ordPens')"           # [not win]
    - "\"%R%\" -e \"library('ordPens')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ordPens
  license: GPL-2.0-only
  summary: Selection and/or smoothing of ordinally scaled independent variables using a group lasso or generalized ridge penalty.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ordPens
# Type: Package
# Title: Selection and/or Smoothing of Ordinal Predictors
# Version: 0.3-1
# Date: 2015-05-21
# Author: Jan Gertheiss
# Maintainer: Jan Gertheiss <jgerthe@uni-goettingen.de>
# Description: Selection and/or smoothing of ordinally scaled independent variables using a group lasso or generalized ridge penalty.
# Depends: grplasso, mgcv, RLRsim, tcltk
# Suggests: IsoGene, Biobase
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2015-05-21 14:03:45 UTC; jgerthe_2
# Repository: CRAN
# Date/Publication: 2015-05-21 16:38:36
